packages:
  - configs/eslint/*
  - configs/prettier/*
  - configs/biome
  - configs/cspell
  - configs/oxlint
catalogs:
  eslint:
    eslint: ^9.22.0
    globals: ^16.0.0
    typescript-eslint: ^8.45.0
  prettier:
    "@ianvs/prettier-plugin-sort-imports": "^4.5.1"
    "prettier": "^3.6.0"
onlyBuiltDependencies:
  - esbuild
