name: PR Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linting
            run: pnpm exec oxlint
          - name: Formatting
            run: pnpm exec oxfmt --check
          - name: Typechecking
            run: pnpm exec tsgo
          - name: Build
            run: pnpm build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ${{ matrix.name }}
        run: ${{ matrix.run }}
